steps:
- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
    - 'HF_CLIENT_ID'
    - 'HF_CLIENT_SECRET'
    - 'HF_REDIRECT_URI'
    - 'GOOGLE_CLIENT_ID'
    - 'GOOGLE_CLIENT_SECRET'
    - 'GOOGLE_REDIRECT_URI'
  args:
    - build
    - -t
    - europe-north1-docker.pkg.dev/$PROJECT_ID/trivia-app/trivia-app-image:latest
    - --build-arg=HF_CLIENT_ID
    - --build-arg=HF_CLIENT_SECRET
    - --build-arg=HF_REDIRECT_URI
    - --build-arg=GOOGLE_CLIENT_ID
    - --build-arg=GOOGLE_CLIENT_SECRET
    - --build-arg=GOOGLE_REDIRECT_URI
    - .
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/trivia-app/trivia-app-image:latest']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./kubernetes/deployment.yaml
  - --image=europe-north1-docker.pkg.dev/$PROJECT_ID/trivia-app/trivia-app-image:latest
  - --location=europe-north1-a
  - --cluster=trivia-cluster
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
availableSecrets:
  secretManager:
  - versionName: projects/179112734170/secrets/HF_CLIENT_ID/versions/latest
    env: 'HF_CLIENT_ID'
  - versionName: projects/179112734170/secrets/HF_CLIENT_SECRET/versions/latest
    env: 'HF_CLIENT_SECRET'
  - versionName: projects/179112734170/secrets/HF_REDIRECT_URI/versions/latest
    env: 'HF_REDIRECT_URI'
  - versionName: projects/179112734170/secrets/GOOGLE_CLIENT_ID/versions/latest
    env: 'GOOGLE_CLIENT_ID'
  - versionName: projects/179112734170/secrets/GOOGLE_CLIENT_SECRET/versions/latest
    env: 'GOOGLE_CLIENT_SECRET'
  - versionName: projects/179112734170/secrets/GOOGLE_REDIRECT_URI/versions/latest
    env: 'GOOGLE_REDIRECT_URI'
timeout: 3600s