apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivia-app
  template:
    metadata:
      labels:
        app: trivia-app
    spec:
      containers:
      - name: trivia-app
        image: europe-north1-docker.pkg.dev/euphoric-hull-451714-q2/trivia-app/trivia-app-image:latest
        ports:
        - containerPort: 7860
        command: ["uvicorn", "app:app", "--port", "7860", "--host", "0.0.0.0"]
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: trivia-app-service
spec:
  selector:
    app: trivia-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: LoadBalancer