apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-app
spec:
  selector:
    matchLabels:
      app: trivia-app
  template:
    metadata:
      labels:
        app: trivia-app
    spec:
      containers:
      - name: trivia-app
        image: europe-north1-docker.pkg.dev/euphoric-hull-451714-q2/trivia-app/trivia-app-image:latest
        ports:
        - containerPort: 7860
        command: ["uvicorn", "app:app", "--port", "7860", "--host", "0.0.0.0"]
      - name: trivia-server1
        image: europe-north1-docker.pkg.dev/euphoric-hull-451714-q2/trivia-app/trivia-server1-image:latest
        ports:
        - containerPort: 8000
      - name: trivia-server2
        image: europe-north1-docker.pkg.dev/euphoric-hull-451714-q2/trivia-app/trivia-server2-image:latest
        ports:
        - containerPort: 7888
---
apiVersion: v1
kind: Service
metadata:
  name: trivia-app-service
spec:
  selector:
    app: trivia-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: trivia-server1-service
spec:
  selector:
    app: trivia-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: trivia-server2-service
spec:
  selector:
    app: trivia-app
  ports:
    - protocol: TCP
      port: 7888
      targetPort: 7888
  clusterIP: None 
